### PR TITLE
git/week2

### PR DESCRIPTION
**Pull request by Rasim-Deniz**

### CODE REVIEW

**Comment by KavyaReddy732** [comment]
Hi Rasim, you need to make PR between git/week2 and feature/veggies.

**Comment by Rasim-Deniz** [comment]
> Hi Rasim, you need to make PR between git/week2 and feature/veggies.

Yes, I did. Did I miss something?

**Comment by KavyaReddy732** [comment]
No your PR is between master and git/week2

**Comment by Rasim-Deniz** [comment]
> No your PR is between master and git/week2

Could you have a look at my new PR to see if it's correct this time please? Here is the link : https://github.com/Rasim-Deniz/hyf-homework/pull/24

**Pull request closed without merging**
